# Generated by Django 5.0.1 on 2024-02-01 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_date_of_birth_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='course_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apps.course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100),
        ),
    ]
