# Generated by Django 5.0.1 on 2024-02-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_department_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.course'),
        ),
    ]
