# Generated by Django 5.0.1 on 2024-02-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_department_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AllotedCourse',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Enrolled',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
